version: "3.8"

services:
  client:
    container_name: frontend
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/smart-brain-web
      - /usr/src/smart-brain-web/node_modules
    networks:
      - react-express
    depends_on:
      - server
    restart: always

  server:
    container_name: backend
    build: ./backend
    environment:
      POSTGRES_URI: postgres://foo:secret@db:5432/smart-brain-db
      REDIS_URI: redis://redis:6379
      JWT_SECRET: shhhhh
    expose:
      - 3000
    volumes:
      - ./backend:/usr/src/smart-brain-api
      - /usr/src/smart-brain-api/node_modules
    networks:
      - express-data
      - react-express
    depends_on:
      - db
      - redis
    restart: always

  db:
    container_name: postgres
    build:
      context: ./database/postgres
      target: development
    environment:
      POSTGRES_USER: foo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-db
    expose:
      - 5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - express-data
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - express-data
    restart: always

networks:
  react-express:
  express-data:
